import Link from "next/link";
import { notFound } from "next/navigation";

const pages: Record<string, { eyebrow: string; title: string; text: string; points: string[] }> = {
  "chauffeur-prive-arras": { eyebrow: "Chauffeur privé à Arras", title: "Un trajet parfaitement à votre rythme.", text: "Pour vos rendez-vous, sorties, retours de voyage ou déplacements du quotidien, VTC ARRAS HDF vous accompagne depuis Arras avec la même attention au détail.", points: ["Prise en charge à l’adresse de votre choix", "Service sur réservation", "Trajets privés et professionnels"] },
  "transfert-aeroport": { eyebrow: "Transferts aéroports", title: "Votre départ commence dans le calme.", text: "Lille-Lesquin, Paris Charles-de-Gaulle, Orly ou Beauvais : votre prise en charge est organisée autour de votre vol, de vos bagages et de vos impératifs.", points: ["Lille-Lesquin et aéroports parisiens", "Horaires anticipés", "Numéro de vol pris en compte"] },
  "transfert-gare": { eyebrow: "Transferts gares", title: "Lorsque votre voyage continue, nous sommes là.", text: "Gare d’Arras, Lille-Flandres, Lille-Europe : évitez les correspondances incertaines et poursuivez votre trajet sereinement.", points: ["Attente adaptée au train communiqué", "Aide avec les bagages", "Départs et arrivées sur réservation"] },
  professionnels: { eyebrow: "Professionnels", title: "Un chauffeur fiable pour vos journées qui comptent.", text: "Vos déplacements d’affaires demandent une organisation sans surprise. Nous assurons vos rendez-vous, transferts et trajets pour vos collaborateurs avec confidentialité.", points: ["Réservation anticipée", "Facturation professionnelle", "Transport de collaborateurs"] },
  evenements: { eyebrow: "Événements", title: "Profiter du moment, dès le départ.", text: "Dîner, cérémonie, événement d’entreprise ou soirée : organisez votre transport avec une solution sobre, ponctuelle et adaptée à votre programme.", points: ["Prise en charge personnalisée", "Disponibilité sur réservation", "Trajets aller et retour"] },
  vehicule: { eyebrow: "Peugeot 508 GT SW Hybride · 2021", title: "Un espace dédié à votre sérénité.", text: "Vos trajets sont assurés à bord d’une Peugeot 508 GT SW Hybride de 2021, confortable et entretenue pour vous permettre de voyager dans le calme.", points: ["Peugeot 508 GT SW Hybride", "Modèle 2021 avec climatisation", "Besoins spécifiques sur demande avant réservation"] },
  "a-propos": { eyebrow: "VTC ARRAS HDF", title: "La simplicité est une forme d’attention.", text: "Derrière chaque trajet, un chauffeur attentif à votre temps, à votre confort et à la discrétion dont vous avez besoin. Une approche directe, humaine et précise.", points: ["Connaissance du territoire", "Conduite souple et discrète", "Un interlocuteur unique"] },
  contact: { eyebrow: "Contact", title: "Parlons de votre prochain trajet.", text: "Indiquez votre départ, votre destination, la date et l’heure souhaitées. Nous reviendrons vers vous rapidement pour organiser votre prise en charge.", points: ["06 82 54 58 49", "vtcarrashdf@gmail.com", "Disponible 24h/24 sur réservation"] },
  faq: { eyebrow: "Questions fréquentes", title: "Toutes les réponses avant votre départ.", text: "Pour toute demande particulière — bagages, enfant, horaires ou transfert longue distance — contactez directement VTC ARRAS HDF.", points: ["Réservation à l’avance recommandée", "Transferts gares et aéroports", "Facture sur demande"] },
  "mentions-legales": { eyebrow: "Informations", title: "Mentions légales", text: "Les informations légales complètes seront publiées par l’entreprise avant la mise en ligne définitive. Pour toute question concernant le site ou le traitement de vos données, contactez VTC ARRAS HDF.", points: ["vtcarrashdf@gmail.com", "06 82 54 58 49"] },
};

export function generateStaticParams() { return Object.keys(pages).map((slug) => ({ slug })); }

export default async function DetailPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params; const page = pages[slug]; if (!page) notFound();
  return <main className="detail-page"><header className="detail-header"><Link prefetch={false} className="brand" href="/"><b>VTC</b> ARRAS HDF</Link><Link prefetch={false} className="button button-small" href="/#reservation">Réserver <i>↗</i></Link></header><section className="detail-hero"><p className="eyebrow">{page.eyebrow}</p><h1>{page.title}</h1><p>{page.text}</p><a className="button button-light" href="tel:+33682545849">Appeler 06 82 54 58 49 <i>↗</i></a></section><section className="detail-content"><p className="eyebrow ink">L’essentiel</p><div>{page.points.map((point, i) => <p className="detail-point" key={point}><span>0{i + 1}</span>{point}</p>)}</div></section><section className="detail-cta"><p>Votre prochain trajet commence ici.</p><Link prefetch={false} className="button button-light" href="/#reservation">Réserver un trajet <i>↗</i></Link></section></main>;
}
